// Generated by CoffeeScript 1.3.3
(function() {
  var assert, index;

  assert = require('assert');

  index = require('../index');

  describe("Using the Hand builder", function() {
    return it("should return a hand with cards sorted", function() {
      var hand;
      hand = new index.Hand.make(["5s", "5c", "5h", "6c", "Ts", "9s", "2d"]);
      return assert.equal(hand.name, "Three of a kind");
    });
  });

  describe("Using Card", function() {
    return it("should return a hand with cards sorted", function() {
      var deck;
      deck = new index.Deck();
      return assert.equal(deck.cards.length, 52);
    });
  });

}).call(this);
